// src/components/layout/divider/Divider.vue
<script lang="ts">
import { useComponentConfig } from '@/composables/use-component-config'
import type { ComponentClass } from '@/types/utils.type'
import { clsx, getClass } from '@/utils/build-class.util'
import { DIVIDER_CONFIG } from './divider.context'
import type { DividerProps } from './divider.props'
import type { DividerColor, DividerOrientation, DividerPlacement } from './divider.types'

const dividerOrientations: ComponentClass<'divider', DividerOrientation> = {
  horizontal: 'divider-horizontal',
  vertical: 'divider-vertical',
}

const dividerColors: ComponentClass<'divider', DividerColor> = {
  neutral: 'divider-neutral',
  primary: 'divider-primary',
  secondary: 'divider-secondary',
  accent: 'divider-accent',
  info: 'divider-info',
  success: 'divider-success',
  warning: 'divider-warning',
  error: 'divider-error',
}

const dividerPlacements: ComponentClass<'divider', DividerPlacement> = {
  start: 'divider-start',
  end: 'divider-end',
}
</script>

<script setup lang="ts">
const props = defineProps<DividerProps>()
const config = useComponentConfig(DIVIDER_CONFIG, props)
</script>

<template>
  <div
    class="divider"
    :class="clsx([
      'w-full',
      getClass(dividerOrientations, config.orientation),
      getClass(dividerColors, config.color),
      getClass(dividerPlacements, config.placement),
    ])"
  >
    <slot />
  </div>
</template>

// packages/core/src/components/divider/divider.tsx
import { Component, type ComponentInterface, Host, Prop, h } from '@stencil/core';
import { componentConfig } from '#config';
import { isRTL } from '#utils/dir.util';
import type { DividerColor, DividerOrientation, DividerPlacement } from './divider.type';

/**
 * Divider will be used to separate content vertically or horizontally.
 *
 * @slot - Text for describe the divider
 */
@Component({
  tag: 'pop-divider',
  styleUrl: 'divider.scss',
  shadow: true,
})
export class Divider implements ComponentInterface {
  /**
   * Define content disposition orientation
   *
   * @config
   * @default "horizontal"
   */
  @Prop({ reflect: true, mutable: true }) orientation: DividerOrientation;

  /**
   * Where to place the content.
   * - `"left"`: The content will appear to the left of the divider in LTR and RTL.
   * - `"start"`: The content will appear to the left of the divider in LTR and to the right in RTL.
   * - `"center"`: The content will appear to the center of the divider.
   * - `"end"`: The content will appear to the right of the divider in LTR and to the left in RTL.
   * - `"right"`: The content will appear to the right of the divider in LTR and RTL.
   *
   * @config
   * @default "center"
   */
  @Prop({ reflect: true, mutable: true }) placement: DividerPlacement;

  /**
   * The color to use from your application's color palette.
   * Default options are: `"primary"`, `"secondary"`, `"accent"`, `"neutral"`, `"info"`, `"success"`, `"warning"`, `"error"`.
   * For more information on colors, see [theming](/docs/theming/basics).
   *
   * @config
   */
  @Prop({ reflect: true, mutable: true }) color: DividerColor;

  componentWillLoad(): void {
    componentConfig.apply(this, 'pop-divider', {
      orientation: 'horizontal',
      placement: 'center',
    });
  }

  render() {
    return (
      <Host
        class={{
          'divider-rtl': isRTL(this),
        }}
      >
        <slot />
      </Host>
    );
  }
}
